vesslai integration
vessl-ai/llama_index_vesslai pull request #1
Opened 2024-12-08 13:37 UTC by nsd9696

# Description

Integrate VESSL AI LLM Serving to Llama Index. Users can simply serve their own huggingface model through vllm with OpenAILike compatible server. Enable following commands.
```
# vessl configure
llm = VesslAILLM()

#1 Serve with methods 
llm.serve(
    organization_name = "vessl-ai",
    service_name = "llama-index-vesslai-test",
    model_name = "mistralai/Mistral-7B-Instruct-v0.3",
)

#2 Serve with yaml
llm.serve(
    organization_name = "vessl-ai",
    service_name = "llama-index-vesslai-test",
    yaml_path="/root/vesslai/vesslai_vllm.yaml",
)

#3 Pre-served endpoint
llm.connect(
    served_model_name="mistralai/Mistral-7B-Instruct-v0.3",
    endpoint="https://serve-api.vessl.ai/api/v1/services/endpoint/v1",
)

resp = llm.complete("Who is Paul Graham?")
print(resp)
```

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Your pull-request will likely not be merged unless it is covered by some form of impactful unit testing.

- [ ] I added new unit tests to cover this change
- [ ] I believe this change is already covered by existing unit tests

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

2024-12-09 00:47 UTC, hippothewild commented
리뷰하는 분을 위해 맥락 공유: https://www.notion.so/vesslai/LlamaIndex-2024-11-08-138bfa25e9fc8094915fd77ea8db8b89?pvs=4#138bfa25e9fc80d5bfd8d269d656ee3d

2024-12-10 07:10 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        service_config['env']['HF_TOKEN'] = hf_token
이거 그냥 env 로 넣나요? secret으로 넣는 게 낫겠습니다.

2024-12-10 07:10 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
얘는 언제 어떻게 쓰일까요? 지금 vLLM 인증 방식이 두 가지인 거 같은데
1. Generic Secret을 ModelService에 연결해서 토큰으로 사용 / Authorization 헤더에 토큰 실어서 인증
2. vLLM 자체적으로 있는 무언가...?

2024-12-10 07:10 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
지금은 따로 쓰이는 곳이 보이진 않는 거 같아요

2024-12-10 07:10 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        )
코드 포매팅 전반적으로 해주세요 예를 들어 여기에는 마지막 줄에 엔터가 들어가야겠죠

2024-12-10 07:27 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
저 openai_api_key 는 OpenAILike 이 친구 때문에 필요합니다. OpenAILike는 나중에 chat completion 같은 동작을 openai 에서 사용하는 동작과 compatible 하게 맞춰주는 역할을 하구요. openai api쓰지 않아도 저 api_key가 있어야, usage tracking이나 security 등 openai 에서 지원하는 3rd party tool을 사용할 수 있어서 필요합니다

2024-12-10 07:37 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        service_config['env']['HF_TOKEN'] = hf_token
유저 입장에서는 vessl org에 secret 을 등록하는 것 보다 local에서 가지고 있는 hf_token을 쓰는게 더 자연스러운 동작일 것 같아서 이렇게 작성하긴 했습니다. hf_token이 hf_ prefix로 시작하니까 해당 값이면 env로 박고 아니면 secret 하는 로직으로 해두겠습니다

2024-12-10 08:47 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        service_config['env']['HF_TOKEN'] = hf_token
넴네 좋아요

2024-12-10 08:48 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
vLLM 액세스 토큰으로써 사용은 안 한다는 뜻일까요?

2024-12-11 05:28 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
아녀 vLLM은 service 를 띄울 때 사용하는 엔진이고, OpenAILike는 띄워진 service_endpoint를 가져다가 OpenAI compatible 하게 사용할 수 있도록 도와줍니다. 이 OpenAILike에서 필요합니다.

2024-12-13 07:42 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
OPENAI_API_TOKEN이라는 이름으로 저희 모델 서비스 찌를 거 같이 생겨서 오해의 여지가 클 거 같아요. 어쩔지 고민이 되네요

2024-12-16 02:11 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
이거 근데 유저입장에서 openai compatible 하게 쓰려면 OpenAILike 를 쓰는게 좋아서.. 어쩔 수 없는 부분인 것 같습니다

2024-12-16 09:27 UTC, Suckzoo commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
OPENAI_API_TOKEN을 시크릿으로 등록하는 건 꺼려지는거죠? 이거만 답변 받고 어프루브 드리겠습니다.

2024-12-16 10:20 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
아 그건 가능합니다. hf-token 과 동일하게 sk- prefix 아니면 secret에서 긁어오는걸로 할게요

2024-12-17 04:06 UTC, Suckzoo approved these changes

2024-12-18 01:52 UTC, hippothewild requested changes

2024-12-18 01:52 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        #2 Serve with yaml
이 옵션은 드랍합시다.

2024-12-18 01:52 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +    def _launch_service_revision_from_yaml(
SDK에서 직접 런치하지 않고, 띄우는 것은 별도로 하고 존재하는 endpoint를 검색만 해서 사용하면 어떨까 합니다.
- YAML 모드로 띄우는 코드는 재실행할때마다 service revision를 계속 생성하고 롤아웃하게 됨
- 리비전이 뜨고 엔드포인트가 준비되는 시간이 O(min)이라, 유저 입장에서 이해하기 어려운 딜레이

차라리 스텝을 나누는게 유저 입장에서 더 납득이 가능하지 않을까 싶어요.

2024-12-18 01:52 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/vesslai_vllm.yaml
> +image: quay.io/vessl-ai/torch:2.3.1-cuda12.1-r5
요거 이제 vllm이라는 이미지가 존재하긴 합니다. 하지만 이렇게 띄우지 않기로 했으니 생략..

2024-12-18 01:52 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/tests/test_llms_vesslai.py
> +def test_embedding_class():
의미있는 코드인가요?

2024-12-18 02:11 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        #2 Serve with yaml
드랍하는 이유가 혹시 있을까요? model_name으로 띄우는 것 만으로는 사용성이 너무 제한될 것 같아서요

2024-12-18 02:14 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +    def _launch_service_revision_from_yaml(
엄 말씀해주신 방향을 처음에 생각했었는데, SDK에서 런치하는게 없어지면 저희가 integration 하는 의미가 많이 없어지는 것 같습니다. 스텝을 나눌까 고민했는데 유저가 그런 복잡한 경험을 원치 않을 것 같아서 일단은 무조건 돌고 있는 revision, rollout 을 abort 하고 띄우는 것으로 해두었습니다.

2024-12-18 02:17 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/tests/test_llms_vesslai.py
> +def test_embedding_class():
큰 의미는 없습니다만 다른 integration 들이랑 일단 동일하게 작성해두었습니다

2024-12-18 02:18 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        #2 Serve with yaml
그리고 밑에 말씀해주신거 생각하면 1번 옵션도 제외하는걸 생각하고 계신가요?

2024-12-19 06:57 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        #2 Serve with yaml
아래쪽 코멘트와 같은 맥락이므로 묶어서 얘기합시다.

2024-12-19 08:08 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +    def _launch_service_revision_from_yaml(
띄워져있는 서비스가 없을때 SDK에서 바로 런치하는 경험을 불편하지 않게 주려면 아래 두개가 전제되어야 할 것 같습니다.
- 서비스를 띄우는 시간이 오래 걸리기 때문에, 유저에게 로그로 최대한 친절하게 안내해서 인내심을 주기 (없어서 띄울거고, 여기 링크에서 상황 확인해보면 된다 등등)
- yaml을 던졌더라도 이미 해당 서비스에 identical한 revision이 있으면 (model ID, image 등을 비교해보면 될것 같습니다) 다시 롤아웃하지 않고 바로 존재하는 endpoint 사용

두개가 전제가 된다면 지금처럼 해도 좋습니다.

2024-12-19 08:10 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/vesslai_vllm.yaml
> +image: quay.io/vessl-ai/torch:2.3.1-cuda12.1-r5
그렇다면 이제 이 코멘트는 의미가 있군요. https://quay.io/repository/vessl-ai/vllm 입니다.

2024-12-19 08:10 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +    def _launch_service_revision_from_yaml(
넵넵 좀더 세심하게 다듬어 보겠습니닷

2024-12-19 08:10 UTC, hippothewild requested changes
ㄱㄱ

2024-12-20 04:46 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        self.api_key = os.environ.get('OPENAI_API_KEY')
이거는 생각해보니까 OpenAILike 를 로컬에서 사용하는거라 로컬에도 openai_key가 필요합니다. secret 긁어서 secret value 까지는 못가져오는 것 같아서 일단은 이렇게 유지하는게 좋을 것 같습니다. 일단 integration 되면 필요하면 마저 진행할게요

2024-12-20 04:52 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +    def _launch_service_revision_from_yaml(
유저에게 확인할 수 있는 서비스 링크, endpoint 전달하도록 했고, 동일한 model_name 이 있으면 해당 model_service connect 해서 사용할 수 있도록 수정했습니다

2024-12-30 02:58 UTC, hippothewild approved these changes
lgtm but couple of nits

2024-12-30 02:58 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/base.py
> +        force: bool = False,
force_relaunch 가 좀더 명확한 네이밍일 것 같습니다

2024-12-30 02:58 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        yaml_dict = yaml.safe_load(running_revision.yaml_spec)
아예 yaml이 identical한걸로 비교해도 되지않을까요?

2024-12-30 02:58 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +def check_service_with_model_name(service_name: str, model_name: str) -> Any:
nit: `ensure_service_idempotence_with_model_name`

2024-12-30 02:58 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/vesslai_vllm.yaml
>  - command: 'pip install autoawq==0.2.6
아마 pip install 전부 필요없을듯/

2024-12-30 06:29 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        yaml_dict = yaml.safe_load(running_revision.yaml_spec)
먼가 description 이 조금 바뀐 내용 때문에 걸리지 않으면 슬플 것 같아서.. 일단 model name 으로 비교하고 원하지 않는 service 면 force 해서 하도록 하는게 낫지 않을까 싶습니다

2024-12-30 06:39 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        yaml_dict = yaml.safe_load(running_revision.yaml_spec)
model_name을 하드코딩할수도 있을것 같아용

2024-12-30 09:04 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        yaml_dict = yaml.safe_load(running_revision.yaml_spec)
넴넴 일단 그럼 yaml 로 비교하겠습니다

2024-12-30 09:05 UTC, hippothewild commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        yaml_dict = yaml.safe_load(running_revision.yaml_spec)
어차피 유저의 패턴이 모델 이름만 넣어서 하는거일거니... 이미지, 모델 네임, 커맨드 정도만 비교해보면 되지않을까 싶긴함다

2024-12-30 09:25 UTC, nsd9696 commented on llama-index-integrations/llms/llama-index-llms-vesslai/llama_index/llms/vesslai/utils.py
> +        yaml_dict = yaml.safe_load(running_revision.yaml_spec)
수정했는데 한번 봐주시면 감사하겠습니당

2024-12-30 13:29 UTC, hippothewild approved these changes
lgtm!

2024-12-31 02:12 UTC, merged